services:
  hcm:
    container_name: hcm
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: host-credential-manager-go:latest
    network_mode: "host"
    volumes:
      - ../data:/root/data
      - ../cert:/root/cert
    restart: always
