version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: host-credential-manager-go:latest
    ports:
      - "8080:8080"
    volumes:
      - ../data:/root/data
    restart: always
